---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: "{{ .Release.Name }}-pg-pvc"
    labels:
        app: "{{ template "t721.fullname" . }}-pg"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
spec:
    volumeName: "{{ .Release.Name }}-pg-pv"
    storageClassName: "standard"
    accessModes:
        - {{ .Values.postgres.persistence.accessMode | quote }}
    resources:
        requests:
            storage: {{ .Values.postgres.persistence.volumeSize | quote }}
