---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: "{{ .Release.Name }}-geth-pvc"
    labels:
        app: "{{ template "t721.fullname" . }}-geth"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
spec:
    volumeName: "{{ .Release.Name }}-geth-pv"
    storageClassName: "standard"
    accessModes:
        - {{ .Values.geth.persistence.accessMode | quote }}
    resources:
        requests:
            storage: {{ .Values.geth.persistence.volumeSize | quote }}
