apiVersion: v1
kind: Service
metadata:
    name: "{{ .Release.Name }}-webapp-svc"
    labels:
        app: "{{ template "t721.fullname" . }}-webapp"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
spec:
    type: {{ .Values.webapp.service.type }}
    ports:
        - port: {{ .Values.webapp.service.port }}
          targetPort: 3000
          protocol: TCP
          name: app
    selector:
        app: "{{ template "t721.fullname" . }}-webapp"
