---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: "{{ .Release.Name }}-cert"
    namespace: default
    labels:
        app: "{{ template "t721.fullname" . }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
spec:
    secretName: "{{ .Release.Name }}-cert-secret"
    dnsNames:
        - {{ .Values.webapp.ingress.host }}
        - {{ .Values.server.ingress.host }}
        - {{ .Values.geth.ingress.host }}
    issuerRef:
        name: "{{ .Release.Name }}-letsencrypt"
        kind: ClusterIssuer
