---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
    name: "{{ .Release.Name }}-letsencrypt"
spec:
    acme:
        server: {{ .Values.letsencrypt.server }}
        email: {{ .Values.letsencrypt.email }}
        privateKeySecretRef:
            name: "{{ .Release.Name }}-letsencrypt-secret"
        http01: {}
