apiVersion: v1
kind: Service
metadata:
    name: "{{ .Release.Name }}-parity-svc"
    labels:
        app: "{{ template "t721.fullname" . }}-parity"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
spec:
    type: {{ .Values.parity.service.type }}
    ports:
        - port: {{ .Values.parity.service.rpcPort }}
          targetPort: 8545
          protocol: TCP
          name: jsonrpc
        - port: {{ .Values.parity.service.listenerPort }}
          targetPort: 30303
          protocol: TCP
          name: listener
        - port: {{ .Values.parity.service.discoveryPort }}
          targetPort: 30303
          protocol: UDP
          name: discovery
    selector:
        app: "{{ template "t721.fullname" . }}-parity"
