env:
    gcp: false

letsencrypt:
    email: iulian@ticket721.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory

postgres:
    config:
        databaseName: ticket721
        databaseUser: ticketer
        databasePassword: super_strong_password
        databasePort: 5432
    persistence:
        gceVolume: pg-disk
        gceVolumeType: ext4
        volumeSize: 20Gi
        accessMode: ReadWriteOnce
    container:
        image: postgres
        version: latest
    service:
        type: ClusterIP

serverModules:
    container:
        image: ticket721/server-modules
        version: latest

server:
    container:
        image: ticket721/server
        version: latest
    service:
        type: NodePort
        port: 1337
    ingress:
        host: api.rinkeby.ticket721.com
        gceIpName: api-public
    persistence:
        gceVolume: strapi-disk
        gceVolumeType: ext4
        volumeSize: 25Gi
        accessMode: ReadWriteOnce

webapp:
    container:
        image: ticket721/webapp
        version: latest
    service:
        type: NodePort
        port: 3000
    config:
        google_api_token: ""
        strapi_endpoint: ""
        tx_explorer: ""
        google_analytics_token: ""
    ingress:
        host: rinkeby.ticket721.com
        gceIpName: webapp-public

nginx:
    rbac:
        create: true
    controller:
        service:
            loadBalancerIP: {}
        ingressClass: "nginx"

geth:
    rinkeby:
        enabled: true
        bootnodes: "enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303"
        networkid: 4
    container:
        image: ethereum/client-go
        version: stable
        network: rinkeby
    service:
        type: NodePort
        rpcPort: 8545
        listenerPort: 30303
        discoveryPort: 30303
    persistence:
        gceVolume: geth-disk
        gceVolumeType: ext4
        volumeSize: 100Gi
        accessMode: ReadWriteOnce
    ingress:
        host: geth.rinkeby.ticket721.com
        gceIpName: geth-public
    cpu:
        limit: 2
        requests: 1.3
    memory:
        limit: 6000Mi
        requests: 4000Mi

